# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: voice-chat.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10voice-chat.proto\x12\tvoicechat\"7\n\x11StreamAzanRequest\x12\x0f\n\x07\x63hat_id\x18\x01 \x01(\x03\x12\x11\n\taudio_url\x18\x02 \x01(\t\"6\n\x12StreamAzanResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\"(\n\x15StartVoiceChatRequest\x12\x0f\n\x07\x63hat_id\x18\x01 \x01(\x03\":\n\x16StartVoiceChatResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\"\'\n\x14StopVoiceChatRequest\x12\x0f\n\x07\x63hat_id\x18\x01 \x01(\x03\"9\n\x15StopVoiceChatResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\"P\n\x10StartCallRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\x03\x12\x11\n\taudio_url\x18\x02 \x01(\t\x12\x18\n\x10\x64uration_seconds\x18\x03 \x01(\x05\"F\n\x11StartCallResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\x0f\n\x07\x63\x61ll_id\x18\x03 \x01(\t\"!\n\x0e\x45ndCallRequest\x12\x0f\n\x07\x63\x61ll_id\x18\x01 \x01(\t\"3\n\x0f\x45ndCallResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\"\x14\n\x12HealthCheckRequest\"&\n\x13HealthCheckResponse\x12\x0f\n\x07healthy\x18\x01 \x01(\x08\x32\xe0\x03\n\x10VoiceChatService\x12I\n\nStreamAzan\x12\x1c.voicechat.StreamAzanRequest\x1a\x1d.voicechat.StreamAzanResponse\x12U\n\x0eStartVoiceChat\x12 .voicechat.StartVoiceChatRequest\x1a!.voicechat.StartVoiceChatResponse\x12R\n\rStopVoiceChat\x12\x1f.voicechat.StopVoiceChatRequest\x1a .voicechat.StopVoiceChatResponse\x12\x46\n\tStartCall\x12\x1b.voicechat.StartCallRequest\x1a\x1c.voicechat.StartCallResponse\x12@\n\x07\x45ndCall\x12\x19.voicechat.EndCallRequest\x1a\x1a.voicechat.EndCallResponse\x12L\n\x0bHealthCheck\x12\x1d.voicechat.HealthCheckRequest\x1a\x1e.voicechat.HealthCheckResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'voice_chat_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_STREAMAZANREQUEST']._serialized_start=31
  _globals['_STREAMAZANREQUEST']._serialized_end=86
  _globals['_STREAMAZANRESPONSE']._serialized_start=88
  _globals['_STREAMAZANRESPONSE']._serialized_end=142
  _globals['_STARTVOICECHATREQUEST']._serialized_start=144
  _globals['_STARTVOICECHATREQUEST']._serialized_end=184
  _globals['_STARTVOICECHATRESPONSE']._serialized_start=186
  _globals['_STARTVOICECHATRESPONSE']._serialized_end=244
  _globals['_STOPVOICECHATREQUEST']._serialized_start=246
  _globals['_STOPVOICECHATREQUEST']._serialized_end=285
  _globals['_STOPVOICECHATRESPONSE']._serialized_start=287
  _globals['_STOPVOICECHATRESPONSE']._serialized_end=344
  _globals['_STARTCALLREQUEST']._serialized_start=346
  _globals['_STARTCALLREQUEST']._serialized_end=426
  _globals['_STARTCALLRESPONSE']._serialized_start=428
  _globals['_STARTCALLRESPONSE']._serialized_end=498
  _globals['_ENDCALLREQUEST']._serialized_start=500
  _globals['_ENDCALLREQUEST']._serialized_end=533
  _globals['_ENDCALLRESPONSE']._serialized_start=535
  _globals['_ENDCALLRESPONSE']._serialized_end=586
  _globals['_HEALTHCHECKREQUEST']._serialized_start=588
  _globals['_HEALTHCHECKREQUEST']._serialized_end=608
  _globals['_HEALTHCHECKRESPONSE']._serialized_start=610
  _globals['_HEALTHCHECKRESPONSE']._serialized_end=648
  _globals['_VOICECHATSERVICE']._serialized_start=651
  _globals['_VOICECHATSERVICE']._serialized_end=1131
# @@protoc_insertion_point(module_scope)
