# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import voice_chat_pb2 as voice__chat__pb2


class VoiceChatServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.StreamAzan = channel.unary_unary(
                '/voicechat.VoiceChatService/StreamAzan',
                request_serializer=voice__chat__pb2.StreamAzanRequest.SerializeToString,
                response_deserializer=voice__chat__pb2.StreamAzanResponse.FromString,
                )
        self.StartVoiceChat = channel.unary_unary(
                '/voicechat.VoiceChatService/StartVoiceChat',
                request_serializer=voice__chat__pb2.StartVoiceChatRequest.SerializeToString,
                response_deserializer=voice__chat__pb2.StartVoiceChatResponse.FromString,
                )
        self.StopVoiceChat = channel.unary_unary(
                '/voicechat.VoiceChatService/StopVoiceChat',
                request_serializer=voice__chat__pb2.StopVoiceChatRequest.SerializeToString,
                response_deserializer=voice__chat__pb2.StopVoiceChatResponse.FromString,
                )
        self.StartCall = channel.unary_unary(
                '/voicechat.VoiceChatService/StartCall',
                request_serializer=voice__chat__pb2.StartCallRequest.SerializeToString,
                response_deserializer=voice__chat__pb2.StartCallResponse.FromString,
                )
        self.EndCall = channel.unary_unary(
                '/voicechat.VoiceChatService/EndCall',
                request_serializer=voice__chat__pb2.EndCallRequest.SerializeToString,
                response_deserializer=voice__chat__pb2.EndCallResponse.FromString,
                )
        self.HealthCheck = channel.unary_unary(
                '/voicechat.VoiceChatService/HealthCheck',
                request_serializer=voice__chat__pb2.HealthCheckRequest.SerializeToString,
                response_deserializer=voice__chat__pb2.HealthCheckResponse.FromString,
                )


class VoiceChatServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def StreamAzan(self, request, context):
        """Group voice chat methods
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StartVoiceChat(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StopVoiceChat(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StartCall(self, request, context):
        """1-on-1 call methods
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def EndCall(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def HealthCheck(self, request, context):
        """Health check
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_VoiceChatServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'StreamAzan': grpc.unary_unary_rpc_method_handler(
                    servicer.StreamAzan,
                    request_deserializer=voice__chat__pb2.StreamAzanRequest.FromString,
                    response_serializer=voice__chat__pb2.StreamAzanResponse.SerializeToString,
            ),
            'StartVoiceChat': grpc.unary_unary_rpc_method_handler(
                    servicer.StartVoiceChat,
                    request_deserializer=voice__chat__pb2.StartVoiceChatRequest.FromString,
                    response_serializer=voice__chat__pb2.StartVoiceChatResponse.SerializeToString,
            ),
            'StopVoiceChat': grpc.unary_unary_rpc_method_handler(
                    servicer.StopVoiceChat,
                    request_deserializer=voice__chat__pb2.StopVoiceChatRequest.FromString,
                    response_serializer=voice__chat__pb2.StopVoiceChatResponse.SerializeToString,
            ),
            'StartCall': grpc.unary_unary_rpc_method_handler(
                    servicer.StartCall,
                    request_deserializer=voice__chat__pb2.StartCallRequest.FromString,
                    response_serializer=voice__chat__pb2.StartCallResponse.SerializeToString,
            ),
            'EndCall': grpc.unary_unary_rpc_method_handler(
                    servicer.EndCall,
                    request_deserializer=voice__chat__pb2.EndCallRequest.FromString,
                    response_serializer=voice__chat__pb2.EndCallResponse.SerializeToString,
            ),
            'HealthCheck': grpc.unary_unary_rpc_method_handler(
                    servicer.HealthCheck,
                    request_deserializer=voice__chat__pb2.HealthCheckRequest.FromString,
                    response_serializer=voice__chat__pb2.HealthCheckResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'voicechat.VoiceChatService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class VoiceChatService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def StreamAzan(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/voicechat.VoiceChatService/StreamAzan',
            voice__chat__pb2.StreamAzanRequest.SerializeToString,
            voice__chat__pb2.StreamAzanResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def StartVoiceChat(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/voicechat.VoiceChatService/StartVoiceChat',
            voice__chat__pb2.StartVoiceChatRequest.SerializeToString,
            voice__chat__pb2.StartVoiceChatResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def StopVoiceChat(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/voicechat.VoiceChatService/StopVoiceChat',
            voice__chat__pb2.StopVoiceChatRequest.SerializeToString,
            voice__chat__pb2.StopVoiceChatResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def StartCall(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/voicechat.VoiceChatService/StartCall',
            voice__chat__pb2.StartCallRequest.SerializeToString,
            voice__chat__pb2.StartCallResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def EndCall(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/voicechat.VoiceChatService/EndCall',
            voice__chat__pb2.EndCallRequest.SerializeToString,
            voice__chat__pb2.EndCallResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def HealthCheck(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/voicechat.VoiceChatService/HealthCheck',
            voice__chat__pb2.HealthCheckRequest.SerializeToString,
            voice__chat__pb2.HealthCheckResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
